favicon: /favicon.ico


# Nav Menus
menu:
    首页: /
    归档: /archives
#    好友: /friends
    关于我: /about

# Nav Shortcut Icons
nav_icons:
    - ['/images/mail.svg', 'mailto:xiaomo@xiaomo.info']
    - ['/images/github.svg', 'https://github.com/xiaomoinfo']
    - ['/images/stackoverflow.svg', 'https://github.com/AngryPowman']
    - ['/images/rss.svg', '/atom.xml']
    - ['/images/zhihu.svg', 'https://www.zhihu.com/people/hupengbest']
    - ['/images/twitter.svg', 'https://twitter.com/hupengbest']


# Friend Links
friend_links:
  - ['小莫,'https://xiaomo.info']
  - ['烧酒博客','https://i.shojo.cc/']
  - ['小野狗','http://fortl.net']
  - ['monstlin','monsterlin.com']
  - ['香菇会长','https://siitake.cn/']
  - ['Edik博客','https://www.edik.cn/']
  - ['贤心博客','http://sentsin.com/']
  - ['冷子欲','http://lengziyu.com/']
  - ['Leonn','https://liyuans.com/']
  - ['netcan','http://www.netcan666.com/']
  - ['kotori','https://kotori.love/']

# About
about_info:
    name: "小莫"
    bio: "日本語を習っています....."
    avatar: "//image.xiaomo.info/logo/avatar.png"

# Comment
# e.g disqus: seansun
disqus: xiaomoblog
duoshuo: 

# Analytics
google_analytics: xiaomoblog
tencent_analytics: 
 
# Copyright Infomation
startyear: 2015
